/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ramp.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export default function Ramp(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/ramp.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={new THREE.MeshBasicMaterial({ color: "green" })}
        position={[0, 3, -20]}
        scale={[10, 3, 10]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/ramp.glb");
