/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rock.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export default function Rock(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("models/rock.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 1.209, 0]}
        scale={2.017}
      />
    </group>
  );
}

useGLTF.preload("/rock.glb");
